name: pyinstaller

on:
  push:
    branches: [ dev, main, build_exe_2 ]
  workflow_dispatch:
jobs:
  build-lin:
    env:
      GITHUB_TOKEN: ${{ secrets.FTP_SERVER }}
    if: contains(github.event.head_commit.message, '[build]') # only run if commit message contains [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-licenses
          pip install pyinstaller
          pip-licenses -f plain-vertical -l --no-license-path -u --from all >> LICENSE
      - name: Build Linux
        run: pyinstaller --onefile aimm.py --add-data 'LICENSE:.' --name aimm --distpath dist/
      - name: Tests
        if: contains(github.event.head_commit.message, '[tests]') # only run if commit message contains [build]
        run: |
          dist/aimm
          dist/aimm init
          dist/aimm add BSRGAN
          dist/aimm list
          dist/aimm remove BSRGAN
          dist/aimm search GFPGAN
      - name: Upload Release Linux
        uses: actions/upload-artifact@v3
        with:
          name: Linux Binary
          path: dist/aimm
      - name: Deploy FTP
        uses: genietim/ftp-action@releases/v4
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "/aimm"

#  build-win:
#    if: contains(github.event.head_commit.message, '[build]') # only run if commit message contains [build]
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install pip-licenses
#        pip-licenses -f plain-vertical -l --no-license-path -u --from all >> LICENSE
#        pip install pyinstaller
#    - name: Build Windows
#      run: pyinstaller --onefile aimm.py --add-data 'LICENSE:.' --name aimm --distpath dist/
#    - name: Tests
#      if: contains(github.event.head_commit.message, '[tests]') # only run if commit message contains [build]
#      run: |
#        dist/aimm
#        dist/aimm init
#        dist/aimm add BSRGAN
#        dist/aimm list
#        dist/aimm remove BSRGAN
#        dist/aimm search GFPGAN
#    - name: Upload Release Windows
#      uses: actions/upload-artifact@v3
#      with:
#        name: Windows Binary
#        path: dist/aimm.exe

#  build-win-installer:
#    if: contains(github.event.head_commit.message, '[build]') # only run if commit message contains [build]
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install pip-licenses
#        pip-licenses -f plain-vertical -l --no-license-path -u --from all >> LICENSE
#        pip install pynsist
#    - name: Build Windows-Installer
#      run: install/win-installer.bat
#    - name: Upload Release Windows-Installer
#      uses: actions/upload-artifact@v3
#      with:
#        name: Windows Installer
#        path: dist/win-installer/
#
#  build-mac:
#    if: contains(github.event.head_commit.message, '[build]') # only run if commit message contains [build]
#    runs-on: macos-11
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install pip-licenses
#        pip-licenses -f plain-vertical -l --no-license-path -u --from all >> LICENSE
#        pip install pyinstaller
#    - name: Build MacOS
#      run: pyinstaller --onefile aimm.py --name aimm --distpath dist/
#    - name: Test
#      run: |
#        dist/aimm
#        dist/aimm init
#        dist/aimm add BSRGAN
#        dist/aimm list
#        dist/aimm remove BSRGAN
#        dist/aimm search GFPGAN
#    - name: Upload ReleaseMacOS
#      uses: actions/upload-artifact@v3
#      with:
#        name: MacOS Binary
#        path: ./aimm
#
#  build-mac-installer:
#    if: contains(github.event.head_commit.message, '[build]') # only run if commit message contains [build]
#    runs-on: macos-11
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install pip-licenses
#        pip-licenses -f plain-vertical -l --no-license-path -u --from all >> LICENSE
#        pip install pyinstaller
#    - name: Build MacOS
#      run: pyinstaller --onefile aimm.py --name aimm --distpath dist/
#    - name: Test
#      run: |
#        dist/aimm
#        dist/aimm init
#        dist/aimm add BSRGAN
#        dist/aimm list
#        dist/aimm remove BSRGAN
#        dist/aimm search GFPGAN
#    - name: Upload ReleaseMacOS
#      uses: actions/upload-artifact@v3
#      with:
#        name: MacOS Binary
#        path: ./aimm